/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_wd_com_demo_bean_myJNI */

#ifndef _Included_test_wd_com_demo_bean_myJNI
#define _Included_test_wd_com_demo_bean_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_wd_com_demo_bean_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
 //就实现了个函数 JNIEnv的用法可以自行百度，这里就不展开了
JNIEXPORT jstring JNICALL Java_test_wd_com_demo_bean_myJNI_sayHello
  (JNIEnv *env, jclass jobj){
        return (*env)->NewStringUTF(env,"JNI hahahahahahahaha");
  }


#ifdef __cplusplus
}
#endif
#endif
